In [ ]:
# https://www.kaggle.com/datasets/algord/fake-news

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('FakeNewsNet.csv')

In [ ]:
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1


In [ ]:
df.shape

(23196, 5)

In [ ]:
df.isnull().sum()

,0
title,0
news_url,330
source_domain,330
tweet_num,0
real,0


In [ ]:
#drop nan values
df = df.dropna()

In [ ]:
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1


In [ ]:
df.shape

(22866, 5)

In [ ]:
# get independent features
X = df.drop('real',axis=1)

In [ ]:
Y = df['real']

In [ ]:
X.shape

(22866, 4)

In [ ]:
X

,title,news_url,source_domain,tweet_num
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38
...,...,...,...,...
23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52
23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7
23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26
23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24


In [ ]:
Y.shape

(22866,)

In [ ]:
Y

,real
0,1
1,1
2,1
3,1
4,1
...,...
23191,1
23192,0
23193,1
23194,0


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.20.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import  pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
# vocabulary size
voc_size = 5000

In [ ]:
### One Hot Representation
messages = X.copy()

In [ ]:
messages['title'][0]

"Kandi Burruss Explodes Over Rape Accusation on 'Real Housewives of Atlanta' Reunion (Video)"

In [ ]:
messages

,title,news_url,source_domain,tweet_num
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38
...,...,...,...,...
23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52
23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7
23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26
23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24


In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

,index,title,news_url,source_domain,tweet_num
0,0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42
1,1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0
2,2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63
3,3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20
4,4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38
...,...,...,...,...,...
22861,23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52
22862,23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7
22863,23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26
22864,23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24


In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# Dataset Preprocessing
from nltk.stem.porter import  PorterStemmer
ps = PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son b

In [ ]:
corpus[0]

'kandi burruss explod rape accus real housew atlanta reunion video'

In [ ]:
corpus[1]

'peopl choic award best red carpet look'

In [ ]:
onehot_rep = [one_hot(words,voc_size) for words in corpus]

In [ ]:
onehot_rep

[[2414, 770, 986, 481, 459, 2867, 3362, 701, 605, 883],
 [4027, 3182, 3187, 3340, 1833, 1579, 2972],
 [2318,
  4705,
  4062,
  1983,
  463,
  3639,
  3486,
  1253,
  365,
  1987,
  759,
  4056,
  3127,
  2114,
  3680],
 [1037, 2553, 4169, 302, 886, 3462, 3989, 2891],
 [1515, 280, 735, 1740, 2069, 133, 3638, 4129, 954, 445, 3495, 681, 1228],
 [694, 4833, 3054, 3378, 1608, 1527, 2902, 4328, 1215],
 [2995, 312, 4981, 1478, 4127, 1140],
 [4110, 2107, 4864, 2295, 1612, 330, 1585, 2811, 589, 1471],
 [553, 4983, 1021, 1693, 2837, 460, 3758, 4264, 1727, 1491, 1987, 759],
 [571, 2614, 3778, 3751, 1930, 1761],
 [3551, 4700, 759, 533, 4504, 3210, 4944, 4795, 687],
 [1953, 1319, 4800, 1217, 2168, 279, 3051],
 [4567, 1318, 4544, 1692, 2661, 3639, 1795, 1334, 3390, 401, 2085, 2463],
 [1934, 2836, 4136, 3509, 2904, 3577],
 [2780, 3069, 3699, 3609, 1833, 148, 4984, 4943],
 [2682, 3037, 867, 3427, 1889, 2161, 2191, 824, 3991, 3639],
 [1464, 2342, 3192, 446, 707, 587, 3672],
 [3136, 3672, 3836, 1103, 28

In [ ]:
onehot_rep[0]

[2414, 770, 986, 481, 459, 2867, 3362, 701, 605, 883]

In [ ]:
corpus[0]

'kandi burruss explod rape accus real housew atlanta reunion video'

In [ ]:
### Embedding
padding_length = 20
embedded_docs = pad_sequences(onehot_rep, padding='post', maxlen=padding_length)


In [ ]:
embedded_docs

array([[2414,  770,  986, ...,    0,    0,    0],
       [4027, 3182, 3187, ...,    0,    0,    0],
       [2318, 4705, 4062, ...,    0,    0,    0],
       ...,
       [1333, 4563, 1472, ...,    0,    0,    0],
       [1695,  779, 2130, ...,    0,    0,    0],
       [3253, 4325, 3344, ...,    0,    0,    0]], dtype=int32)

In [ ]:
embedded_docs[0]

array([2414,  770,  986,  481,  459, 2867, 3362,  701,  605,  883,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
### creating Model
# features = 40
# model = Sequential()
# model.add(Embedding(voc_size,features))
# model.add(LSTM(100))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [ ]:
### Adding Dropout
from tensorflow.keras.layers import Dropout
# creating model
features = 50
model = Sequential()
model.add(Embedding(voc_size,features))
model.add(Dropout(0.3))
model.add(LSTM(200))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model(embedded_docs)
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (22866, 20, 50)        │       250,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (22866, 20, 50)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (22866, 200)           │       200,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (22866, 200)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (22866, 1)             │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 451,001 (1.72 MB)

 Trainable params: 451,001 (1.72 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
len(embedded_docs),Y.shape

(22866, (22866,))

In [ ]:
import numpy as np
X_final = np.array(embedded_docs)
Y_final = np.array(Y)

In [ ]:
X_final.shape , Y_final.shape

((22866, 20), (22866,))

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X_final, Y_final, test_size=0.33, random_state=42)

In [ ]:
## model Training

In [ ]:
model.fit(X_train, Y_train, validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Epoch 1/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7887 - loss: 0.4841 - val_accuracy: 0.8265 - val_loss: 0.4138
Epoch 2/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8460 - loss: 0.3634 - val_accuracy: 0.8334 - val_loss: 0.4070
Epoch 3/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8616 - loss: 0.3299 - val_accuracy: 0.8280 - val_loss: 0.4040
Epoch 4/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8695 - loss: 0.3102 - val_accuracy: 0.8243 - val_loss: 0.4092
Epoch 5/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8772 - loss: 0.2955 - val_accuracy: 0.8240 - val_loss: 0.4151
Epoch 6/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8819 - loss: 0.2807 - val_accuracy: 0.7946 - val_loss: 0.4713
Epoch 7/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8847 - loss: 0.2650 - val_accuracy: 0.8243 - val_loss: 0.4348
Epoch 8/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8972 - loss: 0.2412 - val_accuracy: 

In [ ]:
### Performance Metrics and Accuracy

In [ ]:
Y_prediction = model.predict(X_test)

236/236 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [ ]:
Y_prediction = np.where(Y_prediction> 0.5,1,0)  ## AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(Y_test, Y_prediction)

array([[1073,  769],
       [ 670, 5034]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_prediction)

0.8093029419560032

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_prediction))

              precision    recall  f1-score   support

           0       0.62      0.58      0.60      1842
           1       0.87      0.88      0.87      5704

    accuracy                           0.81      7546
   macro avg       0.74      0.73      0.74      7546
weighted avg       0.81      0.81      0.81      7546

